name: Deploy to VPS
on:
  push:
    branches: [ prod ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
    - name: Pull Latest Changes and Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        command_timeout: "20m"
        script_stop: true
        script: |
          cd /home/ajhelen/smart-tourism-web
          git pull origin prod
          echo "${{ secrets.ENV_FILE }}" > .env
          sudo npm install -g pnpm
          pnpm install
          npx prisma db pull
          npx prisma generate
          pnpm run build
          pm2 restart smart-tourism
